### ISSUE TITLE
Text selection is not visible on iTerm

### ISSUE THREAD

**Issue by chris-fran** [Rigellute/rigel#1]
![rigel-issue](https://user-images.githubusercontent.com/22173137/63779096-9538c800-c8ab-11e9-9cca-950ef83f21f8.gif)

I made a quick tmp fix by swapping Selection and Selected Text colors

**Comment by Rigellute** [comment]
Thanks for pointing this out. Fix here: https://github.com/Rigellute/rigel/commit/61d9e96e487cbbc6074884f4b302d22208cf596e.

Let me know if this works for you! 
<img width="892" alt="image" src="https://user-images.githubusercontent.com/12150276/64082973-a4869e00-cd0f-11e9-8768-66cb9218a302.png">

**Comment by roginfarrer** [comment]
Just chiming in that this works for me 👍
