### ISSUE TITLE
Issue with terminal color

### ISSUE THREAD

**Issue by arashm** [Rigellute/rigel#10]
I think the [last commit](https://github.com/Rigellute/rigel/commit/c6b30f63915788d53446750f7084dc548d5b23ef) has caused some issue with my VIM. Every time I run vim I get the following error:

```
Error detected while processing function <SNR>56_AddAnsiGroups:
line   18:
E254: Cannot allocate color 0
E254: Cannot allocate color 0
Press ENTER or type command to continue
```

That is a function in coc.nvim. It seems like the `g:terminal_ansi_colors` has a wrong value that causes this.

```
:echo g:terminal_ansi_colors
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
```

**Comment by Rigellute** [comment]
Hmmm... Looks like the latest version of `estilo` (which I used in tha last commit) added this line to the [generated vim config](https://github.com/Rigellute/rigel/commit/c6b30f63915788d53446750f7084dc548d5b23ef#diff-9355e59f448739599fb3a534fabb2c70R207)
```vim
if exists('*term_setansicolors')
  let g:terminal_ansi_colors = repeat([0], 16)
endif
```

Will investigate what this is for

**Comment by Rigellute** [comment]
I've reverted to the previous version estilo, which should fix the issue you were facing.

**Comment by arashm** [comment]
Thank you! I don't see the errors anymore.
