### ISSUE TITLE
VS Code Port

### ISSUE THREAD

**Issue by mrmartineau** [Rigellute/rigel#14]
I have created a Rigel port for VS Code. It hasn't been submitted to the Visual Studio Marketplace because I want to get your (@Rigellute) feedback to see if there are any other improvements I can make.

If you want to try it out, download my repo and move the folder into your `~/.vscode/extensions` directory.

https://github.com/mrmartineau/rigel-vscode

Thanks for the great theme by the way 👍

**Comment by Rigellute** [comment]
Wow this is awesome @mrmartineau!! Amazing work! 🎉

Tried it out in VSCode and really looks good. 

Thank you! I'll add your repo to the README

**Comment by mrmartineau** [comment]
That's great. I will try to get it on the marketplace sometime today. Will reply here once it's live.

**Comment by mrmartineau** [comment]
@Rigellute it has just been published to https://marketplace.visualstudio.com/items?itemName=mrmartineau.rigel-vscode 🎉

**Comment by Rigellute** [comment]
Amazing! 🎉🎉🎉 Thank you for doing this!

I'll add this link to the README
