### ISSUE TITLE
In tmux, color is off

### ISSUE THREAD

**Issue by Sammyalhashe** [Rigellute/rigel#3]
I debugged this issue, and it boiled down to this line:

```vim
hi Normal guifg=#e6e6dc ctermfg=254 guibg=#002635 ctermbg=235 gui=NONE cterm=NONE
```
I'm not familiar enough with the semantics of vim colouring to know why this is happening, but I found something similar on reddit: 
https://www.reddit.com/r/neovim/comments/825dj7/the_endless_litany_of_tmux_and_nvim_color_problems/

In here, someone mentions that the line in another colorscheme has this line:
```vim
hi Normal ctermfg=252 ctermbg=235 guifg=#c3d5ec guibg=#1e222c
```

and mentions: "That sets bg=light automatically, Vim helpfully decides that the bg is light, even though `bg=dark` was explicitly set a few lines above".

For context, here are pictures of vim/neovim run with and without the mentioned line in tmux.

With line:
<img width="764" alt="Screen Shot 2019-09-04 at 5 05 52 PM" src="https://user-images.githubusercontent.com/20797997/64291532-68815200-cf36-11e9-9cd1-ad33341c2c9c.png">

Without line:
<img width="762" alt="Screen Shot 2019-09-04 at 5 05 35 PM" src="https://user-images.githubusercontent.com/20797997/64291555-72a35080-cf36-11e9-8391-28d52ce8408d.png">

By the way, beuatiful colorscheme!

**Comment by Rigellute** [comment]
Thanks for this. 

Which terminal emulator are you using?

Are you able to try configuring your shell and tmux like [this](https://github.com/Rigellute/rigel#colours-dont-look-right)? 

That is how I setup my terminal, tmux and vim - and have true color support. Running vim within/without tmux looks the same.

**Comment by Sammyalhashe** [comment]
Hey @Rigellute, thanks for replying! I use iterm2. I made the changes you pointed me to in the README and it seemed to work.
