### ISSUE TITLE
Selection color makes some text hard to read

### ISSUE THREAD

**Issue by muchzill4** [Rigellute/rigel#6]
First of all, thanks for sharing this lovely theme. Amazing work! 😍 

 I'm not sure if it's something wrong with my setup, but the selection color in vim makes certain highlights hard to read (`def` and `return` are barely visible):

![Screenshot 2019-11-01 at 21 41 19](https://user-images.githubusercontent.com/454838/68058424-f2f4f080-fcf0-11e9-98aa-202d6e568846.png)

While the purpose of selecting does not strictly go in line with _reading what's selected_, I was wondering if you'd consider tweaking the selection color a bit.

**Comment by Rigellute** [comment]
Ah interesting! I would be open to tweaking visual mode. I'll see if there is a higher contrast color from the palette.

**Comment by Rigellute** [comment]
Here I'm using a darker colour for highlighting, which should add more contrast?
### Before
<img width="451" alt="image" src="https://user-images.githubusercontent.com/12150276/73138344-75275380-4059-11ea-8aec-8bbd7f90aa9b.png">

### After
<img width="460" alt="image" src="https://user-images.githubusercontent.com/12150276/73138337-56c15800-4059-11ea-8d9b-b4ea3f5914b7.png">

**Comment by Rigellute** [comment]
Fixed here 56e9680c29ff2bf821fc679cd35de4a54c27d75f
